server:
  port: 8080

logging:
  level:
    '[org.springframework]': INFO
    
spring:
  messages:
    basename: messages
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/databasename
    driver-class-name: org.mariadb.jdbc.Driver
    username: username
    password: userpassword
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
 


